# Generated by Django 4.0.6 on 2022-08-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoevent',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='childs', to='cal.todoevent'),
        ),
    ]
