# Generated by Django 4.0.6 on 2022-08-28 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0002_alter_todoevent_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='todoevent',
            options={'ordering': ['duedate', 'duetime']},
        ),
        migrations.AddField(
            model_name='calevent',
            name='others',
            field=models.ManyToManyField(blank=True, related_name='allowedUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calevent',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.eventgroup'),
        ),
    ]
