# Generated by Django 4.0.6 on 2022-08-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_eventgroup_alter_todoevent_options_calevent_others_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
