# Generated by Django 4.0.6 on 2022-08-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_alter_eventgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='name',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
    ]
