# Generated by Django 4.0.6 on 2022-08-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_alter_eventgroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calevent',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='calevent',
            name='time',
        ),
    ]
