# Generated by Django 4.0.6 on 2022-08-28 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0008_alter_calevent_options_remove_calevent_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calevent',
            name='others',
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='others',
            field=models.ManyToManyField(blank=True, related_name='groupUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
