# Generated by Django 4.0.6 on 2022-08-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0011_alter_eventgroup_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calevent',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.eventgroup'),
        ),
    ]
