# Generated by Django 4.0.6 on 2022-08-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0013_alter_eventgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='calevent',
            name='isAnniv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
