# Generated by Django 4.0.6 on 2022-08-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0014_calevent_isanniv_alter_eventgroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calevent',
            name='private',
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
